//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aika.Elasticsearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aika.Elasticsearch.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values were passed to the archive writer for background writing..
        /// </summary>
        internal static string ElasticHistorian_ArchiveWritePendingMessage {
            get {
                return ResourceManager.GetString("ElasticHistorian_ArchiveWritePendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aika historian using Elasticsearch for storage and aggregation..
        /// </summary>
        internal static string ElasticHistorian_Description {
            get {
                return ResourceManager.GetString("ElasticHistorian_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while inserting archive values.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_ArchiveUpdateError {
            get {
                return ResourceManager.GetString("Error_ArchiveUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while writing the snapshot value for the tag.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_SnapshotUpdateError {
            get {
                return ResourceManager.GetString("Error_SnapshotUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A state set with the same name already exists..
        /// </summary>
        internal static string Error_StateSetAlreadyExists {
            get {
                return ResourceManager.GetString("Error_StateSetAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while creating the state set.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_StateSetCreateError {
            get {
                return ResourceManager.GetString("Error_StateSetCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while deleting the state set.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_StateSetDeleteError {
            get {
                return ResourceManager.GetString("Error_StateSetDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified state set does not exist..
        /// </summary>
        internal static string Error_StateSetDoesNotExist {
            get {
                return ResourceManager.GetString("Error_StateSetDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while updating the state set.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_StateSetUpdateError {
            get {
                return ResourceManager.GetString("Error_StateSetUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified tag already exists..
        /// </summary>
        internal static string Error_TagAlreadyExists {
            get {
                return ResourceManager.GetString("Error_TagAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while creating the tag.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_TagCreateError {
            get {
                return ResourceManager.GetString("Error_TagCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while deleting the tag.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_TagDeleteError {
            get {
                return ResourceManager.GetString("Error_TagDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified tag does not exist..
        /// </summary>
        internal static string Error_TagDoesNotExist {
            get {
                return ResourceManager.GetString("Error_TagDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Elasticsearch error occurred while updating the tag.  See the ElasticError property for details..
        /// </summary>
        internal static string Error_TagUpdateError {
            get {
                return ResourceManager.GetString("Error_TagUpdateError", resourceCulture);
            }
        }
    }
}
